Source/WebPortal/Controllers/ServiceBusController.cs
using Microsoft.ServiceBus;
using Microsoft.ServiceBus.Messaging;
using System;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebGrease.Css.Extensions;
using WebPortal.Models;

namespace WebPortal.Controllers
{
    public class ServiceBusController : Controller
    {
        public 
        ActionResult
        Index()
        {
            var defaultOptions = new ServiceBusBenchViewModel
            {
                ServiceSettings     = new ServiceBusServiceSettingsViewModel {
                                        Namespace                       = "Your-Namespace",
                                        AccessKey                       = "Your-Access-Key"
                                    },
                QueueSettings       = new ServiceBusQueueSettingsViewModel {
                                        Path                            = "Your-Queue-Name"
                                    },
                SendParameters = new SendViewModel {
                                        BrokeredMessagePayloadSizeBytes = 1024
                                    },
                ReceiveParameters   = new ReceiveParametersViewModel {
                                        ReceiveMode                     = ReceiveMode.PeekLock
                                    },
                ExecutionSettings   = new ExecutionSettingsViewModel {
                                        NumberOfRepititions             = 1,
                                        MaxDegreeOfParallelism          = 1
                                    }
            };

            return View(defaultOptions);
        }

        public 
        async Task<string>
        Send(
            ServiceBusServiceSettingsViewModel  serviceSettings,
            ServiceBusQueueSettingsViewModel    queueSettings,
            SendViewModel                  sendParameters,
            ExecutionSettingsViewModel          executionSettings)
        {
            try
            {
                var serviceBusConnectionString = string.Format(
                    "Endpoint=sb://{0}.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey={1}",
                    serviceSettings.Namespace,
                    serviceSettings.AccessKey
                    );

                var namespaceManager = NamespaceManager.CreateFromConnectionString(serviceBusConnectionString);

                if (!await namespaceManager.QueueExistsAsync(queueSettings.Path))
                    await namespaceManager.CreateQueueAsync(queueSettings.Path);

                var sendId         = Guid.NewGuid().ToString("N");
                var client         = QueueClient.CreateFromConnectionString(serviceBusConnectionString, queueSettings.Path);
                var payload        = new byte[sendParameters.BrokeredMessagePayloadSizeBytes];
                var totalStopWatch = Stopwatch.StartNew();

                Parallel.For(
                    fromInclusive:      0,
                    toExclusive:        executionSettings.NumberOfRepititions,
                    parallelOptions:    new ParallelOptions {
                                            MaxDegreeOfParallelism = executionSettings.MaxDegreeOfParallelism
                                        },
                    body:               i => client.Send(new BrokeredMessage(payload) { MessageId = sendId + "-" + i })
                );

                var totalElapsedMilliseconds   = totalStopWatch.ElapsedMilliseconds;
                var messagesPerSecond          = executionSettings.NumberOfRepititions / (totalElapsedMilliseconds / 1000.0);
                var averageLatencyMilliseconds = (double)totalElapsedMilliseconds / executionSettings.NumberOfRepititions;
                
                return string.Format(
                    "[{0}] Submitted {1} messages in {2}ms\r\nCalculated Rates: {3}/sec @ {4}ms/msg avg",
                    sendId,
                    executionSettings.NumberOfRepititions,
                    totalElapsedMilliseconds,
                    messagesPerSecond.ToString("0.00"),
                    averageLatencyMilliseconds
                );
            }
            catch (Exception ex)
            {
                return ex.ToString();
            }
        }

        public 
        string
        Receive(
            ServiceBusServiceSettingsViewModel  serviceSettings,
            ServiceBusQueueSettingsViewModel    queueSettings,
            ReceiveParametersViewModel          receiveParameters,
            ExecutionSettingsViewModel          executionSettings)
        {
            try
            {
                var serviceBusConnectionString = FormatConnectionString(serviceSettings);
                var namespaceManager           = NamespaceManager.CreateFromConnectionString(serviceBusConnectionString);

                if (!namespaceManager.QueueExists(queueSettings.Path))
                    namespaceManager.CreateQueue(queueSettings.Path);

                var client = QueueClient.CreateFromConnectionString(
                    serviceBusConnectionString, 
                    queueSettings.Path, 
                    ReceiveMode.ReceiveAndDelete
                );

                var messages = new ConcurrentStack<string>();
                
                var totalStopWatch = Stopwatch.StartNew();

                Parallel.For(
                    fromInclusive:      0,
                    toExclusive:        executionSettings.NumberOfRepititions,
                    parallelOptions:    new ParallelOptions {
                                            MaxDegreeOfParallelism = executionSettings.MaxDegreeOfParallelism
                                        },
                    body:               i => {
                                            var message = client.Receive();

                                            if (message != null)
                                            {
                                                messages.Push(message.MessageId);
                                            }
                                        }
                );

                var totalElapsedMilliseconds   = totalStopWatch.ElapsedMilliseconds;
                var messagesPerSecond          = executionSettings.NumberOfRepititions / (totalElapsedMilliseconds / 1000.0);
                var averageLatencyMilliseconds = (double)totalElapsedMilliseconds / executionSettings.NumberOfRepititions;

                var messageLog = new StringBuilder();

                messages.ForEach(messageId => messageLog.AppendFormat("{0}\r\n", messageId));

                return string.Format(
                    "Received {0} messages in {1}ms\r\nCalculated Rates: {2}/sec @ {3}ms/msg avg:\r\n{4}",
                    executionSettings.NumberOfRepititions,
                    totalElapsedMilliseconds,
                    messagesPerSecond.ToString("0.00"),
                    averageLatencyMilliseconds,
                    messageLog
                );
            }
            catch (Exception ex)
            {
                return ex.ToString();
            }
        }

        private
        string
        FormatConnectionString(
            ServiceBusServiceSettingsViewModel serviceSettings)
        {
            return string.Format(
                "Endpoint=sb://{0}.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey={1}",
                serviceSettings.Namespace,
                serviceSettings.AccessKey
            );
        }
    }

    public class ServiceBusBenchViewModel
    {
        public ServiceBusServiceSettingsViewModel   ServiceSettings     { get; set; }
        public ServiceBusQueueSettingsViewModel     QueueSettings       { get; set; }
        public SendViewModel                        SendParameters      { get; set; }
        public ExecutionSettingsViewModel           ExecutionSettings   { get; set; }
        public ReceiveParametersViewModel           ReceiveParameters   { get; set; }
    }

    public class ServiceBusQueueSettingsViewModel
    {
        public string Path { get; set; }
    }

    public class ReceiveParametersViewModel
    {
        public ReceiveMode ReceiveMode { get; set; }
    }

    public class SendViewModel
    {
        public int BrokeredMessagePayloadSizeBytes { get; set; }
    }

    public class ServiceBusServiceSettingsViewModel
    {
        public string Namespace { get; set; }
        public string AccessKey { get; set; }
    }
}

Source/WebPortal/Views/ServiceBus/Index.cshtml
@model WebPortal.Controllers.ServiceBusBenchViewModel

@{
    ViewBag.Title = "Azure Bench - Service Bus";
}

@section styles
{
    <style type="text/css">
        .Results {
            white-space:        pre-line;
            background-color:   cornflowerblue;
            -ms-border-radius:  10px;
            border-radius:      10px;
            margin-top:         10px;
            padding:            5px;
            font-family:        monospace;
            overflow:           hidden;
        }

        .ServiceBusFunctionPane {
            background-color: lightgray;
            -ms-border-radius:  10px;
            border-radius:      10px;
            padding: 10px;
        }

        .FieldSection {
            margin: 5px;
        }

        .FieldSection label {
            font-weight: lighter;
            float:       left;
            width:       175px;
        }
    </style>
}


<h1>Service Bus</h1>

@Html.LabelFor(model => model.ServiceSettings)
<div class="FieldSection">@Html.EditorFor(model => model.ServiceSettings)</div>

@Html.LabelFor(model => model.QueueSettings)
<div class="FieldSection">@Html.EditorFor(model => model.QueueSettings)</div>

<div id="ServiceBusFunctions">
    <h2>QueueClient.Send</h2>
    <div class="ServiceBusFunctionPane">
        @using (Ajax.BeginForm("Send", "ServiceBus", new AjaxOptions {UpdateTargetId = "SendResults"}))
        {
            @Html.HiddenFor(model => model.ServiceSettings.Namespace)
            @Html.HiddenFor(model => model.ServiceSettings.AccessKey)
            @Html.HiddenFor(model => model.QueueSettings.Path)

            @Html.LabelFor(model => model.SendParameters)
            <div class="FieldSection">@Html.EditorFor(model => model.SendParameters)</div>

            @Html.LabelFor(model => model.ExecutionSettings)
            <div class="FieldSection">@Html.EditorFor(model => model.ExecutionSettings)</div>

            <input type="submit" value="Execute"/>
        }

        <div id="SendResults" class="Results"></div>
    </div>

    <h2>QueueClient.Receive</h2>
    <div class="ServiceBusFunctionPane">
        @using (Ajax.BeginForm("Receive", "ServiceBus", new AjaxOptions { UpdateTargetId = "ReceiveResults" }))
        {
            @Html.HiddenFor(model => model.ServiceSettings.Namespace)
            @Html.HiddenFor(model => model.ServiceSettings.AccessKey)
            @Html.HiddenFor(model => model.QueueSettings.Path)

            @Html.LabelFor(model => model.ReceiveParameters)
            <div class="FieldSection">@Html.EnumDropDownListFor(model => model.ReceiveParameters.ReceiveMode)</div>

            @Html.LabelFor(model => model.ExecutionSettings)
            <div class="FieldSection">@Html.EditorFor(model => model.ExecutionSettings)</div>

            <input type="submit" value="Execute" />
        }

        <div id="ReceiveResults" class="Results"></div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(function() {
            $('#ServiceBusFunctions').accordion({ heightStyle: "content" });
        });

        $('input[type=submit]').click(function() {
            var masterServiceNamespace = $('#ServiceSettings_Namespace').val();
            var masterServiceAccessKey = $('#ServiceSettings_AccessKey').val();

            $(this).siblings('#ServiceSettings_Namespace').val(masterServiceNamespace);
            $(this).siblings('#ServiceSettings_AccessKey').val(masterServiceAccessKey);
        });
    </script>
}