Source/WebPortal/Controllers/RedisCacheController.cs
using StackExchange.Redis;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebPortal.Models;

namespace WebPortal.Controllers
{
    public class RedisCacheController : Controller
    {
        public 
        ActionResult 
        Index()
        {
            var defaultOptions = new RedisBenchViewModel {
                ServiceSettings = new RedisServiceSettingsViewModel {
                    ServiceName = "Your-Service-Name",
                    ServiceKey  = "Your-Service-Key"
                },
                StringSetParameters = new StringSetViewModel {
                    Key   = "Example-Key",
                    Value = "Example-Value"
                },
                StringGetParameters = new StringGetViewModel {
                    Key   = "Example-Key"
                },
                ExecutionSettings = new ExecutionSettingsViewModel {
                    NumberOfRepititions      = 1,
                    MaxDegreeOfParallelism = 1,
                }
            };

            return View(defaultOptions);
        }

        public
        string
        StringSet(
            RedisServiceSettingsViewModel   serviceSettings,
            StringSetViewModel              stringSetParameters,
            ExecutionSettingsViewModel      executionSettings)
        {
            return ExecuteRedisFunction(
                serviceSettings:    serviceSettings,
                redisFunction:      redisDb => redisDb.StringSet(
                                        stringSetParameters.Key, 
                                        stringSetParameters.Value
                                    ),
                executionSettings:  executionSettings
            );
        }

        public
        string
        StringGet(
            RedisServiceSettingsViewModel   serviceSettings,
            StringGetViewModel              stringGetParameters,
            ExecutionSettingsViewModel      executionSettings)
        {
            return ExecuteRedisFunction(
                serviceSettings:    serviceSettings, 
                redisFunction:      redisDb => redisDb.StringGet(
                                        stringGetParameters.Key
                                    ), 
                executionSettings:  executionSettings
            );
        }

        private 
        static
        string 
        ExecuteRedisFunction(
            RedisServiceSettingsViewModel   serviceSettings,
            Action<IDatabase>               redisFunction,
            ExecutionSettingsViewModel      executionSettings)
        {
            try
            {
                var redisDb = GetRedisDb(serviceSettings);

                var totalStopWatch = Stopwatch.StartNew();

                Parallel.For(
                    fromInclusive:      0,
                    toExclusive:        executionSettings.NumberOfRepititions,
                    parallelOptions:    new ParallelOptions {
                                            MaxDegreeOfParallelism = executionSettings.MaxDegreeOfParallelism
                                        },
                    body:               i => redisFunction(redisDb)
                );

                var totalElapsedMilliseconds    = totalStopWatch.ElapsedMilliseconds;
                var documentsPerSecond          = executionSettings.NumberOfRepititions / (totalElapsedMilliseconds / 1000.0);
                var averageLatencyMilliseconds  = (double)totalElapsedMilliseconds / executionSettings.NumberOfRepititions;

                return string.Format(
                    "Processed: {0} items in {1}ms\r\nRate: {2}/sec\r\nLatency: {3}ms avg. per request",
                    executionSettings.NumberOfRepititions,
                    totalElapsedMilliseconds,
                    documentsPerSecond.ToString("0.00"),
                    averageLatencyMilliseconds
                );
            }
            catch (Exception exception)
            {
                return exception.ToString();
            }
        }

        private 
        static 
        IDatabase 
        GetRedisDb(
            RedisServiceSettingsViewModel serviceSettings)
        {
            var configurationString = string.Format(
                "{0}.redis.cache.windows.net,password={1}",
                serviceSettings.ServiceName,
                serviceSettings.ServiceKey
            );

            return ConnectionMultiplexer
                .Connect(configurationString)
                .GetDatabase();
        }
    }

    public class RedisBenchViewModel
    {
        [DisplayName("Service Settings")]   public RedisServiceSettingsViewModel    ServiceSettings     { get; set; }
        [DisplayName("StringSet Settings")] public StringSetViewModel               StringSetParameters { get; set; }
        [DisplayName("StringGet Settings")] public StringGetViewModel               StringGetParameters { get; set; }
        [DisplayName("Execution Settings")] public ExecutionSettingsViewModel       ExecutionSettings   { get; set; }
    }

    public class RedisServiceSettingsViewModel
    {
        public string ServiceName   { get; set; }
        public string ServiceKey    { get; set; }
    }

    public class StringSetViewModel
    {
        public string Key              { get; set; }
        public string Value            { get; set; }
    }

    public class StringGetViewModel
    {
        public string Key { get; set; }
    }
}

Source/WebPortal/Views/RedisCache/Index.cshtml
@model WebPortal.Controllers.RedisBenchViewModel

@{
    ViewBag.Title = "Azure Bench - Redis Cache";
}

@section styles
{
    <style type="text/css">
        .Results {
            white-space:        pre-line;
            background-color:   cornflowerblue;
            -ms-border-radius:  10px;
            border-radius:      10px;
            margin-top:         10px;
            padding:            5px;
            font-family:        monospace;
            overflow:           hidden;
        }

        .RedisFunctionPane {
            background-color: lightgray;
            -ms-border-radius:  10px;
            border-radius:      10px;
            padding: 10px;
        }

        .FieldSection {
            margin: 5px;
        }

        .FieldSection label {
            font-weight: lighter;
            float:       left;
            width:       175px;
        }
    </style>
}

<h1>Redis Cache</h1>

@Html.LabelFor(model => model.ServiceSettings)
<div class="FieldSection">@Html.EditorFor(model => model.ServiceSettings)</div>

<div id="RedisFunctions">
    <h2>StringSet</h2>
    <div class="RedisFunctionPane">
        @using (Ajax.BeginForm("StringSet", "RedisCache", new AjaxOptions { UpdateTargetId = "StringSetResults" }))
        {
            @Html.HiddenFor(model => model.ServiceSettings.ServiceName)
            @Html.HiddenFor(model => model.ServiceSettings.ServiceKey)

            @Html.LabelFor(model  => model.StringSetParameters)
            <div class="FieldSection">@Html.EditorFor(model => model.StringSetParameters)</div>

            @Html.LabelFor(model  => model.ExecutionSettings)
            <div class="FieldSection">@Html.EditorFor(model => model.ExecutionSettings)</div>

            <input type="submit" value="Execute"/>
        }

        <div id="StringSetResults" class="Results"></div>
    </div>

    <h2>StringGet</h2>
    <div class="RedisFunctionPane">
        @using (Ajax.BeginForm("StringGet", "RedisCache", new AjaxOptions { UpdateTargetId = "StringGetResults" }))
        {
            @Html.HiddenFor(model => model.ServiceSettings.ServiceName)
            @Html.HiddenFor(model => model.ServiceSettings.ServiceKey)

            @Html.LabelFor(model => model.StringGetParameters)
            <div class="FieldSection">@Html.EditorFor(model => model.StringGetParameters)</div>
            
            @Html.LabelFor(model  => model.ExecutionSettings)
            <div class="FieldSection">@Html.EditorFor(model => model.ExecutionSettings)</div>

            <input type="submit" value="Execute" />
        }

        <div id="StringGetResults" class="Results"></div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(function() {
            $('#RedisFunctions').accordion({heightStyle:"content"});
        });

        $('input[type=submit]').click(function() {
            var masterServiceName = $('#ServiceSettings_ServiceName').val();
            var masterServiceKey  = $('#ServiceSettings_ServiceKey').val();

            $(this).siblings('#ServiceSettings_ServiceName').val(masterServiceName);
            $(this).siblings('#ServiceSettings_ServiceKey').val(masterServiceKey);
        });
    </script>
}